In [3]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [11]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression


In [12]:
steps=[("standard_Scaler",StandardScaler()),
       ("classifier",LogisticRegression())]

In [13]:
steps

[('standard_Scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [14]:
pipe=Pipeline(steps)

In [15]:
from sklearn import set_config

In [16]:
set_config(display="diagram")

In [17]:
pipe

Pipeline(steps=[('standard_Scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [23]:
from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1000)

In [24]:
X.shape

(1000, 20)

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.33,random_state=42)

In [26]:
X_train

array([[ 8.54772192e-01,  1.38654856e+00, -1.48993222e+00, ...,
         7.66014457e-01, -1.85974461e-01, -1.63840622e+00],
       [ 5.71501433e-02, -7.10200825e-01,  1.01302696e+00, ...,
         1.84900073e+00, -9.12696283e-01,  5.35140009e-01],
       [-3.38626543e-01,  1.03240516e+00, -9.08849900e-01, ...,
         1.35858287e+00, -9.33659365e-01, -4.58274422e-04],
       ...,
       [-1.01198455e+00,  1.21794328e+00,  1.25439478e-01, ...,
         1.51655769e+00,  8.35233365e-01,  6.55590162e-01],
       [ 1.05207348e+00,  5.59359795e-01,  6.73610905e-01, ...,
         1.18581262e+00, -1.16969656e+00, -2.97637008e-01],
       [-1.74858590e+00,  8.06143833e-01, -2.62045670e+00, ...,
        -6.64124712e-01,  9.37725931e-01, -3.37188301e-01]],
      shape=(670, 20))

In [27]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('standard_Scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [28]:
Pipeline(steps=[('standard_scaler', StandardScaler()),
 ('classifier', LogisticRegression())])

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [29]:
y_pred=pipe.predict(X_test)


In [30]:
y_pred

array([0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,

In [31]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [39]:
steps=[("scaling",StandardScaler()),
 ("PCA",PCA(n_components=3)),
 ("SVC",SVC())]


In [40]:
pipe2=Pipeline(steps)


In [41]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [42]:
Pipeline(steps=[('scaling', StandardScaler()), ('PCA',
PCA(n_components=3)),
 ('SVC', SVC())])


Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [43]:
pipe2.predict(X_test)

array([0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,

In [44]:
from sklearn.impute import SimpleImputer

In [45]:
import numpy as np
numeric_processor=Pipeline(

steps=[("imputation_mean",SimpleImputer(missing_values=np.nan,strategy
="mean")),
 ("scaler",StandardScaler())]
)

In [46]:
numeric_processor


Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [48]:
from sklearn.preprocessing import OneHotEncoder


In [50]:
categorical_processor=Pipeline(

steps=[("imputation_consatnt",SimpleImputer(fill_value="missing",strategy="constant")),
 ("onehot",OneHotEncoder(handle_unknown="ignore"))]
)

In [51]:
categorical_processor

Pipeline(steps=[('imputation_consatnt',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [52]:
Pipeline(steps=[('imputation_consatnt',
 SimpleImputer(fill_value='missing',
strategy='constant')),
 ('onehot', OneHotEncoder(handle_unknown='ignore'))])

Pipeline(steps=[('imputation_consatnt',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [53]:
from sklearn.compose import ColumnTransformer

In [54]:
preprocessor=ColumnTransformer(
 [("categorical",categorical_processor,["gender","City"]),
 ("numerical",numeric_processor,["age","height"])]
)


In [55]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_consatnt',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [57]:
ColumnTransformer(transformers=[('categorical',
Pipeline(steps=[('imputation_consatnt',
SimpleImputer(fill_value='missing',
strategy='constant')),
                ('onehot',

OneHotEncoder(handle_unknown='ignore'))]),
 ['gender', 'City']),
 ('numerical',
 Pipeline(steps=[('imputation_mean',
 SimpleImputer()),
 ('scaLER',
  StandardScaler())]),
 ['age', 'height'])])

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_consatnt',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaLER', StandardScaler())]),
                                 ['age', 'height'])])

In [58]:
from sklearn.pipeline import make_pipeline

In [59]:
pipe=make_pipeline(preprocessor,LogisticRegression())

In [60]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_consatnt',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])

In [61]:
Pipeline(steps=[('columntransformer',
 ColumnTransformer(transformers=[('categorical',
Pipeline(steps=[('imputation_consatnt',
SimpleImputer(fill_value='missing',
strategy='constant')),
('onehot',
OneHotEncoder(handle_unnknown='ignore'))]),
 ['gender', 'City']),
 ('numerical',

Pipeline(steps=[('imputation_mean',

SimpleImputer()),

('scaler',
StandardScaler())]),
 ['age',
'height'])])),
 ('logisticregression', LogisticRegression())])

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'handle_unnknown'. Did you mean 'handle_unknown'?